---
title: "rnoaa - Weather"
author: "Lisa Li"
date: "6/6/2019"
output: html_document
---

```{r setup, include=FALSE}
install.packages("rnoaa")
library(rnoaa)

# API
# https://www.ncdc.noaa.gov/cdo-web/webservices/v2
# Request Token
# https://www.ncdc.noaa.gov/cdo-web/token

token <- "HwBsMEMqmFNTjXSjlQixMMiegOBwMRfi"

options(noaakey = token)

list <- ncdc_stations(limit = 1000)

list <- as.data.frame(list$data)
# Hourly Precipitation data for ZIP code 28801
ncdc(datasetid='PRECIP_HLY', locationid='ZIP:28801', datatypeid='HPCP',
startdate = '2010-05-01', enddate = '2010-05-10')

# Hourly Precipitation data for ZIP code 28801
test <- ncdc(datasetid='PRECIP_HLY',  datatypeid='HPCP',
startdate = '2010-05-01', enddate = '2010-05-10')

see <- test$data

# Fetch list of city locations in descending order
test <- ncdc_locs(locationcategoryid='CITY', sortfield='name', sortorder='asc')

test <- test$data

```

```{r exploring}
# Fetch list of city locations in descending order
ncdc_locs(locationcategoryid='CITY', sortfield='name', sortorder='desc')

ncdc_locs_cats()

loc <- ncdc_locs(limit = 1000)
test <- loc$data

zip <- ncdc_locs(locationcategoryid='ZIP', sortfield='name', sortorder='desc')

# Get info on a station by specifcying a dataset, locationtype, location, and station
ncdc_stations(datasetid='GHCND', locationid='FIPS:12017', stationid='GHCND:USC00084289')

# Search for data
out <- ncdc(datasetid='NORMAL_DLY', stationid='GHCND:USW00014895', datatypeid='dly-tmax-normal', startdate = '2010-05-01', enddate = '2010-05-10')

ncdc_datacats(locationid='CITY:US390029')

ncdc(datasetid='PRECIP_HLY', locationid='ZIP:28801', datatypeid='HPCP',
startdate = '2010-05-01', enddate = '2010-05-10')

ncdc_datasets()
ncdc_datacats(datasetid='GHCND')
ncdc_datatypes(datasetid='GHCND')

ncdc(datasetid='GHCND', locationid='ZIP:33139', datatypeid='PRCP',
startdate = '2018-05-01', enddate = '2018-05-10')

# See a data.frame
head( out$data )

# Plot data, super simple, but it's a start
out <- ncdc(datasetid='GHCND', stationid='GHCND:USW00014895', datatypeid='PRCP', startdate = '2010-05-01', enddate = '2010-10-31', limit=500)
ncdc_plot(out, breaks="1 month", dateformat="%d/%m")


# More plotting
# You can pass many outputs from calls to the noaa function in to the ncdc_plot function.

out1 <- ncdc(datasetid='GHCND', stationid='GHCND:USW00014895', datatypeid='PRCP', startdate = '2010-03-01', enddate = '2010-05-31', limit=500)
out2 <- ncdc(datasetid='GHCND', stationid='GHCND:USW00014895', datatypeid='PRCP', startdate = '2010-09-01', enddate = '2010-10-31', limit=500)
ncdc_plot(out1, out2, breaks="45 days")

# Get table of all datasets
ncdc_datasets()

# Get data category data and metadata
ncdc_datacats(locationid='CITY:US390029')

argo_search("nf", limit = 3)
argo_search("np", limit = 3)
argo_search("list", "dac")

x <- argo_buoy_files(dac = "meds", id = 4900881)
argo(dac = "meds", id = 4900881, cycle = 127, dtype = "D")

# data
out1 <- ncdc(datasetid='GHCND', locationid = 'FIPS:02', startdate = '2010-05-01',
enddate = '2010-05-31', limit=10)
out2 <- ncdc(datasetid='GHCND', locationid = 'FIPS:02', startdate = '2010-07-01',
enddate = '2010-07-31', limit=10)
ncdc_combine(out1, out2)

# data sets
out1 <- ncdc_datasets(datatypeid='TOBS')
out2 <- ncdc_datasets(datatypeid='PRCP')
ncdc_combine(out1, out2)

# data types
out1 <- ncdc_datatypes(datatypeid="ACMH")
out2 <- ncdc_datatypes(datatypeid='PRCP')
ncdc_combine(out1, out2)

# data categories
out1 <- ncdc_datacats(datacategoryid="ANNAGR")
out2 <- ncdc_datacats(datacategoryid='PRCP')
ncdc_combine(out1, out2)

# data locations
out1 <- ncdc_locs(locationcategoryid='ST', limit=52)
out2 <- ncdc_locs(locationcategoryid='CITY', sortfield='name', sortorder='desc')
ncdc_combine(out1, out2)

# data locations
out1 <- ncdc_locs_cats(startdate='1970-01-01')
out2 <- ncdc_locs_cats(locationcategoryid='CLIM_REG')
ncdc_combine(out1, out2)

# stations
out1 <- ncdc_stations(datasetid='GHCND', locationid='FIPS:12017',
stationid='GHCND:USC00084289')
out2 <- ncdc_stations(stationid='COOP:010008')
out3 <- ncdc_stations(datasetid='PRECIP_HLY', startdate='19900101',
enddate='19901231')
out4 <- ncdc_stations(datasetid='GHCND', locationid='FIPS:12017')
ncdc_combine(out1, out2, out3, out4)

# try to combine two different classes
out1 <- ncdc_locs_cats(startdate='1970-01-01')
out2 <- ncdc_stations(stationid='COOP:010008')
out3 <- ncdc_locs_cats(locationcategoryid='CLIM_REG')
output <- ncdc_combine(out1, out2, out3)

```

